### ISSUE TITLE
would you mind introduce  "train_synthText.py" file?

### ISSUE THREAD

**Issue by whereitogo** [denabazazian/SoftPHOC_TextDescriptor#1]

**Comment by denabazazian** [comment]
You can find the details of this implementation in this paper: https://arxiv.org/pdf/1809.00854v2.pdf
`train_synthText.py` is a training process that inspired mainly from DeepLabV3, and there is a world descriptor module as SoftPHOC which is generated in `dataloaders/generate_segLabels_synthText` . We have made the experiments in ICDAR2015 and Synthetic datasets.

**Comment by whereitogo** [comment]
@denabazazian thanks！
